

export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_ERROR = "SET_ERROR";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_SELECTED_OPTION = "SET_SELECTED_OPTION";
export const SET_IS_CORRECT = "SET_IS_CORRECT";
export const SET_TOTAL_MARKS = "SET_TOTAL_MARKS";
export const SET_TIMER = "SET_TIMER";
export const SET_QUIZ_STARTED = "SET_QUIZ_STARTED";
export const SET_TOTAL_POSSIBLE_MARKS = "SET_TOTAL_POSSIBLE_MARKS";
export const SET_QUIZ_ENDED = "SET_QUIZ_ENDED";
export const RESTORE_STATE = "RESTORE_STATE";
